import type { Review } from "./types";

export const RESTAURANT_REVIEWS: Review[] = [
  {
    id: "rest-1",
    platform: "google",
    author: "Danielle R.",
    rating: 5,
    text: "The braised short rib risotto at Amara Kitchen was easily the best thing I've eaten all year, creamy and rich with the meat falling apart at the touch of a fork. We lingered over dessert because the room is just so cozy.",
    date: "2026-05-03",
    topics: ["food quality", "ambiance"],
    responded: true,
    responseText: "Thank you so much, Danielle! That short rib risotto is a labor of love in our kitchen, and we're thrilled it landed. Come linger with us anytime, dessert is always better when there's no rush.",
    respondedAt: "2026-05-04",
  },
  {
    id: "rest-2",
    platform: "yelp",
    author: "Marcus Webb",
    rating: 5,
    text: "Came in for our anniversary and the whole team made it special. The seared scallops with corn puree were perfect, and our server Elena flagged the truffle oil for me since I'm not a fan, a small thing that meant a lot.",
    date: "2026-06-18",
    topics: ["food quality", "service"],
    responded: true,
    responseText: "Marcus, congratulations again to you both, we're honored you chose Amara Kitchen for the occasion. I'll make sure Elena hears how much that attention meant; it's exactly how we like to host.",
    respondedAt: "2026-06-19",
  },
  {
    id: "rest-3",
    platform: "facebook",
    author: "Priya N.",
    rating: 4,
    text: "Solid neighborhood spot. The wood-fired margherita and the burrata starter were great, and portions were generous for the price. Took a little while to get water refills, but nothing that would stop me coming back.",
    date: "2026-07-05",
    topics: ["service", "value"],
    responded: true,
    responseText: "Thanks, Priya! Glad the margherita and burrata hit the mark, those are house favorites for good reason. We'll tighten up on the water refills and hope to welcome you back to Amara Kitchen soon.",
    respondedAt: "2026-07-06",
  },
  {
    id: "rest-4",
    platform: "google",
    author: "Tom Halloran",
    rating: 5,
    text: "Amara Kitchen's duck confit is worth the trip alone. Crispy skin, tender underneath, and the cherry gastrique cut right through the richness.",
    date: "2026-06-02",
    topics: ["food quality"],
    sampleReply: "Tom, you just described exactly what we're chasing with that duck — crisp skin, tender underneath, and a gastrique bright enough to cut the richness. It's one of the dishes I'm proudest of, so this really lands. Come back hungry!",
    responded: false,
  },
  {
    id: "rest-5",
    platform: "google",
    author: "Sofia Delgado",
    rating: 5,
    text: "Booked a table for eight for my mom's birthday and everything went off without a hitch. The private nook by the window made it feel intimate even with a big group.",
    date: "2026-04-27",
    topics: ["reservations", "ambiance"],
    sampleReply: "Sofia, hosting your mom's birthday was a joy — that window nook is our little secret for making a big table feel intimate. Thank you for letting Amara Kitchen be part of the celebration; we'd love to have the whole group back anytime.",
    responded: false,
  },
  {
    id: "rest-6",
    platform: "yelp",
    author: "Greg V.",
    rating: 4,
    text: "Great food, and the mushroom pappardelle is a must-order. Only knock is we waited about 25 minutes past our reservation time on a Friday, but the meal made up for it.",
    date: "2026-05-20",
    topics: ["food quality", "wait time"],
    sampleReply: "So glad the mushroom pappardelle won you over, Greg — it's a personal favorite of mine. You're right that 25 minutes past your reservation is too long, even on a busy Friday, and we're tightening up our timing. Thanks for letting the meal make up for the wait.",
    responded: false,
  },
  {
    id: "rest-7",
    platform: "facebook",
    author: "Aisha Karim",
    rating: 3,
    text: "Food was good but the kitchen was clearly slammed, over an hour between our appetizers and our mains. Our server was apologetic and kind about it, at least.",
    date: "2026-06-25",
    topics: ["wait time", "service"],
    sampleReply: "Aisha, an hour between courses is a real gap, and I'm sorry the kitchen's rush landed on your table. I'm glad your server looked after you kindly through it — she'll hear that from me. We're taking a hard look at our pacing on busy nights so the food comes out when it should.",
    responded: false,
  },
  {
    id: "rest-8",
    platform: "google",
    author: "Nathan Cole",
    rating: 3,
    text: "Decent bistro but a bit pricey for what you get. The branzino was cooked well, just a pretty small portion for $34.",
    date: "2026-05-11",
    topics: ["value", "food quality"],
    sampleReply: "Thank you for the honest note, Nathan. The branzino was cooked right, by your account, but a portion that leaves you questioning the price isn't the experience we want — I'm bringing that straight to the kitchen. I hope you'll give us another try so we can show you the value we're capable of.",
    responded: false,
  },
  {
    id: "rest-9",
    platform: "yelp",
    author: "Brett M.",
    rating: 1,
    text: "Waited 40 minutes for a table we had reserved, then another hour for food that came out cold. Nobody seemed to care. Won't be back.",
    date: "2026-07-09",
    topics: ["service", "wait time"],
    sampleReply: "Brett, this is a hard one to read, and I'm sorry — a reserved table shouldn't mean a 40-minute wait, and food should never reach you cold. That's not the Amara Kitchen we work to be. Please email me directly so I can understand what went wrong that night and earn a better visit from you.",
    responded: false,
  },
  {
    id: "rest-10",
    platform: "facebook",
    author: "Kimberly Ross",
    rating: 2,
    text: "Disappointing visit. Our table was sticky when we sat down, and there was a hair in my pasta. The manager took the dish off the bill, but the whole thing put us off.",
    date: "2026-06-30",
    topics: ["cleanliness", "food quality"],
    sampleReply: "Kimberly, a sticky table and a hair in your pasta are exactly the things we should never let slip, and I'm genuinely sorry. Taking the dish off the bill was the least we could do, but it doesn't undo the evening. I'd welcome the chance to have you back and show you the standard we hold ourselves to — please reach out to me directly.",
    responded: false,
  },
];

export const SALON_REVIEWS: Review[] = [
  {
    id: "salon-1",
    platform: "google",
    author: "Rachel T.",
    rating: 5,
    text: "Bianca gave me the balayage of my dreams, natural and sun-kissed and exactly like the reference photo I brought in. The head massage at the shampoo bowl was the cherry on top.",
    date: "2026-05-08",
    topics: ["color", "staff"],
    responded: true,
    responseText: "Rachel, this made our whole day! Bianca lives for a good balayage, and we'll pass along your kind words. We can't wait to keep that sun-kissed glow going at Lumen Salon & Spa, see you next visit!",
    respondedAt: "2026-05-09",
  },
  {
    id: "salon-2",
    platform: "yelp",
    author: "Monica P.",
    rating: 5,
    text: "Best haircut I've had in years. Devon actually listened to what I wanted instead of doing his own thing, and the curtain bangs came out perfect.",
    date: "2026-06-14",
    topics: ["haircut", "staff"],
    responded: true,
    responseText: "Monica, thank you! Devon is all about the consultation, so it means a lot to hear he nailed the brief. Those curtain bangs will grow out beautifully too, we're here whenever you need a trim.",
    respondedAt: "2026-06-15",
  },
  {
    id: "salon-3",
    platform: "facebook",
    author: "Jenna L.",
    rating: 4,
    text: "Loved my gel manicure and the facial afterward. Booking online was easy and they took me right on time. Knocked off a star only because parking around the block is a nightmare.",
    date: "2026-07-02",
    topics: ["spa", "booking"],
    responded: true,
    responseText: "Thanks so much, Jenna! We're thrilled the mani and facial left you glowing. You're right that parking is tricky, there's a lot behind the building we can point you to next time. See you soon at Lumen!",
    respondedAt: "2026-07-03",
  },
  {
    id: "salon-4",
    platform: "google",
    author: "Carla D.",
    rating: 5,
    text: "Lumen Salon & Spa is my happy place. The lavender pedicure and the relaxation room with tea afterward make it feel like a real escape from a long week.",
    date: "2026-04-22",
    topics: ["spa"],
    sampleReply: "Carla, calling us your happy place might be the best compliment we could ask for! That lavender pedicure and a quiet cup of tea in the relaxation room are made for exactly this — melting a long week away. We'll keep the escape ready for you at Lumen.",
    responded: false,
  },
  {
    id: "salon-5",
    platform: "google",
    author: "Steph M.",
    rating: 5,
    text: "Went in for a color correction after a box-dye disaster and walked out with a gorgeous even brunette. Priya worked actual magic and was so reassuring the entire time.",
    date: "2026-06-05",
    topics: ["color", "staff"],
    sampleReply: "Steph, box-dye rescues are Priya's specialty, and she'll be so glad to hear how reassured you felt in her chair. Going from a disaster to a gorgeous even brunette is exactly the magic we love pulling off. Come see us to keep that color looking its best!",
    responded: false,
  },
  {
    id: "salon-6",
    platform: "yelp",
    author: "Olivia B.",
    rating: 4,
    text: "Great cut and blowout, genuinely talented stylists. Prices are on the higher side, but you get what you pay for here.",
    date: "2026-05-25",
    topics: ["haircut", "value"],
    sampleReply: "Thank you, Olivia! We're thrilled the cut and blowout lived up to the chair. Our stylists put real craft into every visit, and it means a lot that you feel the value comes through. We'd love to keep you looking sharp at Lumen.",
    responded: false,
  },
  {
    id: "salon-7",
    platform: "facebook",
    author: "Grace H.",
    rating: 3,
    text: "The spa services themselves are lovely, but I've had trouble twice now with my appointment time getting moved without much notice.",
    date: "2026-06-28",
    topics: ["booking", "spa"],
    sampleReply: "Grace, we're glad the spa services themselves have treated you well — but having your appointment moved twice without proper notice is a frustration we owe you better on. We're tightening how our front desk handles schedule changes so it doesn't keep happening. Thank you for flagging it honestly.",
    responded: false,
  },
  {
    id: "salon-8",
    platform: "google",
    author: "Renee F.",
    rating: 3,
    text: "Decent haircut, but I waited almost 30 minutes past my appointment time. The stylist was great once I was actually in the chair.",
    date: "2026-05-16",
    topics: ["wait time", "haircut"],
    sampleReply: "Thanks for the honest feedback, Renee. A near 30-minute wait past your booking isn't the experience we want to run, even when the cut lands well in the end. We're working on keeping our timing tighter so your stylist's talent is the only thing you're waiting on. Glad you loved the result.",
    responded: false,
  },
  {
    id: "salon-9",
    platform: "yelp",
    author: "Tara S.",
    rating: 1,
    text: "Asked for a trim and two inches off, and came out with a bob I never wanted. The stylist didn't listen at all and I left in tears.",
    date: "2026-07-11",
    topics: ["haircut", "staff"],
    sampleReply: "Tara, I'm so sorry — walking out with a bob when you asked for a two-inch trim is a serious miss, and leaving in tears is the last thing we ever want. That's not the listening our chairs should be known for. Please call and ask for our manager so we can talk it through and support you however we can while it grows back.",
    responded: false,
  },
  {
    id: "salon-10",
    platform: "facebook",
    author: "Bethany K.",
    rating: 2,
    text: "My color came out patchy and brassy, nothing like the photo I asked for. I had to go somewhere else to get it fixed.",
    date: "2026-06-21",
    topics: ["color"],
    sampleReply: "Bethany, patchy and brassy is nowhere near the color you showed us, and I completely understand the disappointment. Color is where we hold ourselves to the highest bar, and we clearly fell short for you. Please reach out to us directly — we'd genuinely like to understand what went wrong and make it right.",
    responded: false,
  },
];

export const DENTAL_REVIEWS: Review[] = [
  {
    id: "dental-1",
    platform: "google",
    author: "Michael S.",
    rating: 5,
    text: "I've had dental anxiety my whole life, and Dr. Reyes and her team made my crown appointment completely painless. They walked me through every single step.",
    date: "2026-05-01",
    topics: ["bedside manner", "pain management"],
    responded: true,
    responseText: "Michael, thank you for trusting us with your care. We know dental anxiety is real, and it means the world that you felt at ease. Dr. Reyes and the whole Bright Harbor Dental team are always in your corner, see you at your next checkup!",
    respondedAt: "2026-05-02",
  },
  {
    id: "dental-2",
    platform: "yelp",
    author: "Laura V.",
    rating: 5,
    text: "Took both my kids in for cleanings and the hygienists were so patient and gentle. My daughter actually asked when she can go back.",
    date: "2026-06-10",
    topics: ["kids", "bedside manner"],
    responded: true,
    responseText: "Laura, this is exactly what we hope for! Our team loves making dental visits something kids look forward to. Please give your daughter a high-five from all of us at Bright Harbor Dental, we'll see the whole family soon.",
    respondedAt: "2026-06-11",
  },
  {
    id: "dental-3",
    platform: "facebook",
    author: "Derek A.",
    rating: 4,
    text: "Great family practice. Scheduling was easy and they got my whole family in on the same afternoon. The only reason it's not five stars is the waiting room can get crowded.",
    date: "2026-07-07",
    topics: ["scheduling", "kids"],
    responded: true,
    responseText: "Thanks, Derek! We're glad the scheduling worked out for the whole family, that afternoon block is a favorite of ours too. We hear you on the waiting room and are always working to keep things comfortable. See you next time at Bright Harbor Dental!",
    respondedAt: "2026-07-08",
  },
  {
    id: "dental-4",
    platform: "google",
    author: "Susan Q.",
    rating: 5,
    text: "Dr. Patel did my root canal and I felt nothing at all. I had been dreading it for weeks, and it turned out to be the easiest appointment I've had.",
    date: "2026-04-24",
    topics: ["pain management", "bedside manner"],
    sampleReply: "Susan, we love hearing this — root canals carry such a scary reputation, and Dr. Patel takes real pride in making them comfortable. Going from weeks of dread to your easiest appointment yet is exactly what we hope for. Thank you for trusting us at Bright Harbor Dental.",
    responded: false,
  },
  {
    id: "dental-5",
    platform: "google",
    author: "Anthony R.",
    rating: 5,
    text: "Been coming here for six years. The front desk knows me by name, the cleanings are thorough, and they never push unnecessary work on you.",
    date: "2026-05-19",
    topics: ["bedside manner"],
    sampleReply: "Six years of visits and we still look forward to seeing you, Anthony! Knowing our patients by name and only recommending the care you actually need is the heart of how we practice. Thank you for the loyalty and the kind words — see you at the next cleaning.",
    responded: false,
  },
  {
    id: "dental-6",
    platform: "yelp",
    author: "Nicole W.",
    rating: 4,
    text: "Solid dental office. My filling was quick and painless. Billing took a couple of calls to sort out with my insurance, but the staff were helpful about it.",
    date: "2026-06-03",
    topics: ["billing", "pain management"],
    sampleReply: "Nicole, we're glad the filling was quick and comfortable! Insurance billing can absolutely take a few calls to untangle, and we're always looking for ways to smooth that out — thank you for your patience with it. It's good to know the team was helpful along the way.",
    responded: false,
  },
  {
    id: "dental-7",
    platform: "facebook",
    author: "Kevin B.",
    rating: 3,
    text: "The care is good, but I've waited well past my appointment time on more than one visit. The cleaning itself was fine.",
    date: "2026-06-27",
    topics: ["wait time"],
    sampleReply: "Thank you for the honest feedback, Kevin. We're glad the care itself has been good, but waiting well past your scheduled time, more than once, is something we take seriously. We're working on keeping our appointments running closer to on-time so your visits respect your day.",
    responded: false,
  },
  {
    id: "dental-8",
    platform: "google",
    author: "Marie L.",
    rating: 3,
    text: "The dentist was competent, but the visit felt rushed and I didn't get much time to ask my questions. Nice enough staff though.",
    date: "2026-05-13",
    topics: ["bedside manner", "wait time"],
    sampleReply: "Marie, thank you for sharing this. You should never leave the chair with unanswered questions, and I'm sorry the visit felt rushed — your time to ask matters just as much as the treatment itself. We're reminding our team to build in that space, and we'd welcome you back for the unhurried visit you deserve.",
    responded: false,
  },
  {
    id: "dental-9",
    platform: "yelp",
    author: "Paul H.",
    rating: 1,
    text: "Got a surprise bill months later for a procedure they told me was covered. Nobody warned me and the billing office was no help at all. Frustrating experience.",
    date: "2026-07-10",
    topics: ["billing"],
    sampleReply: "Paul, a surprise bill months later, for care you were told was covered, is genuinely frustrating, and I'm sorry the billing office left you without answers. That's not the clarity our patients should ever have to chase. Please call the office and ask for our billing manager directly so we can look into it and get you a real explanation.",
    responded: false,
  },
  {
    id: "dental-10",
    platform: "facebook",
    author: "Gina T.",
    rating: 2,
    text: "Long wait, and the crown they did came loose within a week. I had to come back twice to get it right.",
    date: "2026-06-22",
    topics: ["wait time", "scheduling"],
    sampleReply: "Gina, I'm sorry — a long wait and a crown that came loose within a week, with two trips back to fix it, is far from the experience we want for you. A new crown should settle in and stay put. Please reach out to the office and ask for our office manager so we can make sure it's right and spare you any more back-and-forth.",
    responded: false,
  },
];

export const HOME_REVIEWS: Review[] = [
  {
    id: "home-1",
    platform: "google",
    author: "Dave K.",
    rating: 5,
    text: "AC died during the July heat wave and Summit Comfort had a tech out the same day. Carlos found the bad capacitor, replaced it, and we were cool again in under an hour. No upsell, just fixed it.",
    date: "2026-07-08",
    topics: ["emergency service", "punctuality"],
    responded: true,
    responseText: "Appreciate it, Dave. Carlos is one of our best, and same-day service in a heat wave is exactly what we aim for. Glad you're comfortable again, call Summit Comfort anytime you need us.",
    respondedAt: "2026-07-09",
  },
  {
    id: "home-2",
    platform: "yelp",
    author: "Linda M.",
    rating: 5,
    text: "Had our furnace replaced last winter and just had them back for a plumbing leak under the sink. Honest pricing both times, and they showed up exactly when they said they would.",
    date: "2026-05-06",
    topics: ["pricing", "punctuality"],
    responded: true,
    responseText: "Thank you, Linda. Repeat customers like you are why we do this. We'll always give it to you straight on price and show up on time, that's the deal. Thanks for trusting Summit Comfort with both jobs.",
    respondedAt: "2026-05-07",
  },
  {
    id: "home-3",
    platform: "facebook",
    author: "Robert P.",
    rating: 4,
    text: "Good work on our new water heater install. They cleaned up after themselves and explained the maintenance. Docked a star because the final quote came in a bit higher than the phone estimate.",
    date: "2026-06-16",
    topics: ["quality", "cleanup"],
    responded: true,
    responseText: "Thanks for the honest review, Robert. Glad the install went smooth and the crew left it tidy, that's how we operate. Fair point on the phone estimate; we'll be tighter on those numbers up front. Appreciate your business.",
    respondedAt: "2026-06-18",
  },
  {
    id: "home-4",
    platform: "google",
    author: "Janet S.",
    rating: 5,
    text: "Summit Comfort tuned up our AC and swapped a worn belt for a fair price. The tech was on time and walked me through everything he did.",
    date: "2026-04-20",
    topics: ["pricing", "punctuality"],
    sampleReply: "Glad we could get your AC tuned up and that worn belt swapped without any surprises on the bill, Janet. Showing up on time and walking you through the work is just how we do it. Thanks for the review — call Summit Comfort whenever you need us.",
    responded: false,
  },
  {
    id: "home-5",
    platform: "google",
    author: "Frank D.",
    rating: 5,
    text: "These guys are the real deal. They diagnosed a thermostat wiring issue two other companies completely missed, and fixed it in twenty minutes.",
    date: "2026-05-28",
    topics: ["quality"],
    sampleReply: "Appreciate that, Frank. A thermostat wiring gremlin like that trips up a lot of folks, so we're glad we spotted what the other two missed and had you sorted in twenty minutes. That's the job done right. Thanks for calling Summit Comfort.",
    responded: false,
  },
  {
    id: "home-6",
    platform: "yelp",
    author: "Ellen R.",
    rating: 4,
    text: "Reliable and professional. They cleared our clogged main line and left the area clean. Communication about the arrival window could be a little sharper.",
    date: "2026-06-08",
    topics: ["cleanup", "communication"],
    sampleReply: "Thanks, Ellen. Glad we got that main line cleared and left the area clean — that part matters to us. You're right that our arrival window could be sharper, and we're working on keeping folks better posted on timing. Appreciate the honest feedback.",
    responded: false,
  },
  {
    id: "home-7",
    platform: "facebook",
    author: "Gary L.",
    rating: 3,
    text: "Job got done, but they had to reschedule on me once and the tech showed up near the very end of the window. The work itself was fine.",
    date: "2026-06-26",
    topics: ["punctuality", "communication"],
    sampleReply: "Fair feedback, Gary, and thanks for it. Rescheduling on you once and then rolling in at the tail end of the window isn't the reliability we hang our name on. The work held up, but we owe you better on timing, and we're tightening it up. Appreciate your patience.",
    responded: false,
  },
  {
    id: "home-8",
    platform: "google",
    author: "Wendy A.",
    rating: 3,
    text: "They fixed the heating issue, but it took two visits and the pricing felt a little high for the time actually spent.",
    date: "2026-05-14",
    topics: ["pricing", "quality"],
    sampleReply: "Thanks for the honest review, Wendy. Two visits to fix the heat, and a price that felt steep for the time spent, isn't the value we aim to deliver. We're taking a look at how we scope jobs like yours so the cost lines up with the work. Glad the heat's running right now.",
    responded: false,
  },
  {
    id: "home-9",
    platform: "yelp",
    author: "Chuck B.",
    rating: 1,
    text: "Charged me $450 for a part I later found out costs $60, and the AC broke again a week later. Called three times for a callback and got nothing.",
    date: "2026-07-12",
    topics: ["pricing", "communication"],
    sampleReply: "Chuck, this one's on us across the board — a price that far out of line, a repair that didn't hold, and three calls with nobody getting back to you. That's not how Summit Comfort is supposed to run. Please call the office and ask for the owner directly; I want to go over that charge and get your AC actually fixed.",
    responded: false,
  },
  {
    id: "home-10",
    platform: "facebook",
    author: "Diane F.",
    rating: 2,
    text: "The tech tracked mud through the house and left the old parts sitting in my yard. The repair worked, but the mess was unacceptable.",
    date: "2026-06-23",
    topics: ["cleanup", "quality"],
    sampleReply: "Diane, you're absolutely right — mud tracked through your house and old parts left in the yard is unacceptable, and I'm sorry. A working repair doesn't excuse leaving your home worse than we found it. Please give the office a call and ask for a manager so we can make it right and make sure our crew never leaves a mess like that again.",
    responded: false,
  },
];
